---
replicaCount: 1

image:
  repository: ghcr.io/international-data-spaces-association/dataspace-connector-route-test-backend
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "ci"

podAnnotations:
  seccomp.security.alpha.kubernetes.io/pod: "runtime/default"

podSecurityContext: {}

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: "8"
    memory: "4Gi"
  requests:
    cpu: "250m"
    memory: "1Gi"

nodeSelector: {}

tolerations: []

affinity: {}
