name: End to end tests
on:
  pull_request:
    branches: [ main ]

jobs:
  build-test-image:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v2
      -
        name: Build registry path
        id: get_repo
        run: echo ::set-output name=IMAGE::"ghcr.io/international-data-spaces-association/dataspace-connector"
      -
       name: Login to registry
       uses: docker/login-action@v1
       with:
         # This should use REGISTRY instead of the secret directly
         registry: ${{ secrets.IMAGE_REGISTRY }}
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
      -
       name: Build image
       run: |
        docker build . -t $IMAGE:ci
       env:
         IMAGE: ${{ steps.get_repo.outputs.IMAGE }}
      -
       name: Push branch image
       run: |
         docker push $IMAGE:ci
       env:
         IMAGE: ${{ steps.get_repo.outputs.IMAGE }}

  e2e:
    needs: build-test-image
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup environment
        run: |
          curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 sh -
          cat /etc/rancher/k3s/k3s.yaml
          mkdir -p ~/.kube
          cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
      - name: Test environment
        run: |
          kubectl cluster-info
      - name: Run scripts
        run: |
          ./scripts/ci/e2e/setup-provider-consumer.sh
