name: Linting

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Docker
      uses: hadolint/hadolint-action@v1.5.0
      with:
        dockerfile: Dockerfile
        config: .hadolint.yaml
    - name: Lint Docker and Yaml
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        quiet: true
        output_format: github_failed_only
        download_external_modules: true
        soft_fail: true
